default_install_hook_types:
  - prepare-commit-msg
  - commit-msg
  - pre-commit
  - pre-push

default_stages: [pre-commit, pre-push]

fail_fast: false

repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        description: ruff linting
        entry: bash -c "cd page && exec poetry run ruff check"
        pass_filenames: false
        language: system
        types: [python]
        files: ^page/


