# Generated by Django 4.1.8 on 2023-04-30 20:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_language'),
        ('dictionary', '0003_pronunciation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('definition', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part_of_speech', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='definitions', to='dictionary.partofspeech')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='definitions', to='core.source')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='definitions', to='dictionary.word')),
            ],
            options={
                'ordering': ['definition'],
            },
        ),
    ]
