# Generated by Django 4.1.9 on 2023-06-04 16:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_state'),
        ('dictionary', '0005_definition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.CharField(blank=True, max_length=256, null=True)),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('example', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=2048, null=True)),
                ('year', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('definition', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='examples', to='dictionary.definition')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dictionary_examples', to='core.source')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='examples', to='dictionary.word')),
            ],
            options={
                'ordering': ['example'],
            },
        ),
    ]
