# Generated by Django 4.1.8 on 2023-04-30 20:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_relationtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('left_word', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='left_translations', to='dictionary.word')),
                ('relation_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='relations', to='dictionary.relationtype')),
                ('right_word', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='right_translations', to='dictionary.word')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
