# Generated by Django 4.1.8 on 2023-04-30 20:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_language'),
        ('dictionary', '0007_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='source_translations', to='core.language')),
                ('source_word', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='source_word_translations', to='dictionary.word')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='target_translations', to='core.language')),
                ('target_word', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='target_word_translations', to='dictionary.word')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
