# Generated by Django 4.1.9 on 2023-06-04 16:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_state'),
        ('dictionary', '0007_relationtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('left_word', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='left_relations', to='dictionary.word')),
                ('relation_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='relations', to='dictionary.relationtype')),
                ('right_word', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='right_relations', to='dictionary.word')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dictionary_relations', to='core.source')),
            ],
            options={
                'ordering': ['relation_type'],
            },
        ),
    ]
