# Generated by Django 4.1.9 on 2023-06-04 16:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_state'),
        ('dictionary', '0008_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dictionary_translations', to='core.source')),
                ('source_language', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dictionary_source_translations', to='core.language')),
                ('source_word', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='source_word_translations', to='dictionary.word')),
                ('target_language', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dictionary_target_translations', to='core.language')),
                ('target_word', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='target_word_translations', to='dictionary.word')),
            ],
            options={
                'ordering': ['source'],
            },
        ),
    ]
