# Generated by Django 4.1.8 on 2023-04-28 22:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('type', models.CharField(max_length=32)),
                ('subtype', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=32)),
                ('extra', models.CharField(blank=True, max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['type', 'subtype'],
                'unique_together': {('ref', 'type', 'subtype')},
            },
        ),
    ]
