# Generated by Django 4.1.9 on 2023-06-20 23:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_state'),
        ('users', '0005_coordinate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw', models.CharField(blank=True, max_length=256, null=True)),
                ('formatted', models.CharField(blank=True, max_length=256, null=True)),
                ('type', models.CharField(blank=True, choices=[('HOME', 'home'), ('WORK', 'work')], default=None, max_length=16, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='addresses', to='users.coordinate')),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='addresses', to='users.locality')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='users_addresses', to='core.source')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='addresses', to='users.street')),
            ],
            options={
                'ordering': ('locality', 'street'),
            },
        ),
    ]
