[tool.poetry]
name = "django-project"
version = "0.0.1"
description = ""
authors = ["Roman <iamromandev@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.9.16"
loguru = "^0.6.0"
django = "3.2.18"
django-environ = "^0.10.0"
pymysql = "1.0.2"
django-browser-reload = "^1.7.0"
django-tailwind = "^3.5.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
