[tool.poetry]
name = "django-project"
version = "0.0.1"
description = ""
authors = ["Roman <iamromandev@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.9.16"
loguru = "0.6.0"
django = "4.1.8"
django-environ = "0.10.0"
pymysql = "1.0.3"
django-browser-reload = "1.7.0"
#django-tailwind = "3.5.0"
dj-static = "0.0.6"
django-bootstrap5 = "23.1"
django-bootstrap-icons = "0.8.3"
django-soft-delete = "0.9.21"
django-taggit = "3.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
