[tool.poetry]
name = "django-project"
version = "0.0.1"
description = ""
authors = ["Roman <iamromandev@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.9.12"
loguru = "^0.6.0"
django = "^4.1.7"
django-environ = "^0.10.0"
pymysql = "^1.0.2"
django-compressor = "^4.3.1"
django-tailwind = "^3.5.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
