fail_fast: false
repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: poetry
        args: ["run", "ruff", "check", "--fix"]
        types: [python]
        language: system
        require_serial: true

      - id: format
        name: format
        entry: poetry
        language: python
        args: ["run", "ruff", "format"]
        types: [python]

      - id: mypy
        name: mypy
        entry: poetry
        args: ['run', 'mypy']
        exclude: '(__pycache__|.venv|.mypycache)'
        types: [python]
        language: system
        require_serial: true
