# Generated by Django 4.1.9 on 2025-03-28 14:30

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('type', models.CharField(blank=True, choices=[('country', 'Country'), ('state_province', 'State/Province'), ('division', 'Division'), ('district', 'District'), ('city', 'City'), ('county', 'County'), ('municipality', 'Municipality'), ('region', 'Region'), ('address', 'Address'), ('territory', 'Territory'), ('autonomous_region', 'Autonomous Region'), ('union_territory', 'Union Territory'), ('village', 'Village'), ('prefecture', 'Prefecture'), ('zone', 'Zone'), ('postal', 'Postal'), ('neighborhood', 'Neighborhood'), ('landmark', 'Landmark')], max_length=32, null=True)),
                ('address', models.CharField(blank=True, max_length=512, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.location')),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
                'ordering': ['name'],
            },
        ),
    ]
