# Generated by Django 4.1.9 on 2025-04-04 11:47

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_coordinate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('type', models.CharField(blank=True, choices=[('country', 'Country'), ('state_province', 'State/Province'), ('division', 'Division'), ('district', 'District'), ('city', 'City'), ('county', 'County'), ('upazila', 'Upazila'), ('union', 'Union'), ('municipality', 'Municipality'), ('city_corporation', 'City Corporation'), ('town', 'Town'), ('village', 'Village'), ('region', 'Region'), ('address', 'Address'), ('territory', 'Territory'), ('autonomous_region', 'Autonomous Region'), ('union_territory', 'Union Territory'), ('prefecture', 'Prefecture'), ('zone', 'Zone'), ('postal', 'Postal'), ('neighborhood', 'Neighborhood'), ('landmark', 'Landmark'), ('other', 'Other')], max_length=32, null=True)),
                ('continent', models.CharField(blank=True, choices=[('africa', 'Africa'), ('antarctica', 'Antarctica'), ('asia', 'Asia'), ('europe', 'Europe'), ('north_america', 'North America'), ('south_america', 'South America'), ('australia_oceania', 'Australia/Oceania'), ('other', 'Other')], max_length=32, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='core.coordinate')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.location')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['name'],
            },
        ),
    ]
