# Generated by Django 4.1.9 on 2025-04-12 18:50

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(unique=True)),
                ('type', models.CharField(blank=True, choices=[('terms_of_service', 'Terms of Service'), ('privacy_policy', 'Privacy Policy'), ('cookie_policy', 'Cookie Policy'), ('refund_policy', 'Refund Policy'), ('return_policy', 'Return Policy'), ('community_guidelines', 'Community Guidelines'), ('dispute_resolution', 'Dispute Resolution Policy'), ('gdpr_compliance', 'GDPR Compliance'), ('eula', 'End User License Agreement'), ('aup', 'Acceptable Use Policy'), ('sla', 'Service Level Agreement'), ('api_docs', 'API Documentation'), ('api_terms', 'API Terms of Use'), ('developer_portal', 'Developer Portal'), ('support_center', 'Support Center'), ('contact_us', 'Contact Us'), ('help_center', 'Help Center'), ('security_policy', 'Security Policy'), ('trust_center', 'Trust Center'), ('bug_bounty', 'Bug Bounty Program'), ('pricing', 'Pricing'), ('promotions', 'Promotions'), ('case_studies', 'Case Studies'), ('about_us', 'About Us'), ('careers', 'Careers'), ('press_kit', 'Press Kit'), ('blog', 'Blog'), ('website', 'Website'), ('social_media', 'Social Media'), ('other', 'Other')], max_length=32, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('slug', models.SlugField(blank=True, max_length=128, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urls', to='core.language')),
            ],
            options={
                'verbose_name': 'URL',
                'verbose_name_plural': 'URLs',
                'ordering': ['url'],
            },
        ),
    ]
