# Generated by Django 5.2 on 2025-04-20 11:58

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=128, null=True)),
                ('type', models.CharField(blank=True, choices=[('SOCIAL_MEDIA', 'Social Networking (e.g., Facebook, Instagram)'), ('streaming', 'Video/Audio Streaming (e.g., YouTube, Netflix)'), ('messaging', 'Instant Messaging (e.g., WhatsApp, Telegram)'), ('blogging', 'Content Publishing (e.g., Medium, WordPress)'), ('forums', 'Community Discussion (e.g., Reddit, Quora)'), ('gaming', 'Video Game Platforms (e.g., Steam, PlayStation)'), ('ecommerce', 'Online Shopping (e.g., Amazon, Shopify)'), ('business', 'Workplace Tools (e.g., Slack, Salesforce)'), ('education', 'Learning Environments (e.g., Coursera, Moodle)'), ('entertainment', 'Media Consumption (e.g., Spotify, Netflix)'), ('developer', 'Software Development (e.g., GitHub, AWS)'), ('health_fitness', 'Wellness and Fitness (e.g., Fitbit, Calm)'), ('financial', 'Financial Management (e.g., PayPal, Robinhood)'), ('crowdfunding', 'Fundraising Platforms (e.g., Kickstarter)'), ('travel_booking', 'Travel Services (e.g., Expedia, Airbnb)'), ('real_estate', 'Property Listings (e.g., Zillow, Realtor.com)'), ('dating', 'Online Dating (e.g., Tinder, Bumble)'), ('news_aggregator', 'News Collection (e.g., Flipboard, Feedly)'), ('other', 'Other')], max_length=32, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='platform_logos/')),
                ('founded_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_url', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_platform', to='core.url')),
                ('url', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform', to='core.url')),
            ],
            options={
                'verbose_name': 'Platform',
                'verbose_name_plural': 'Platforms',
                'ordering': ['name'],
            },
        ),
    ]
