name: Ruff - Lint

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches: [ main ]

env:
  POETRY_HOME: /opt/poetry
  POETRY_VERSION: 2.1.2
  WORK_DIR: page/src

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Set up python 3.13.2
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13.2

      - name: Update pip
        id: update-pip
        run: pip install --upgrade pip

      - name: Install uv
        id: install-uv
        run: pip install uv

      - name: Set up virtual environment with uv
        id: setup-uv
        run: uv venv

      - name: Install dependencies
        id: install-deps
        run: uv pip install -r /home/runner/work/web/web/page/pyproject.toml

      - name: Install ruff
        id: install-ruffl
        run: uv tool install ruff

      - name: Run Ruff and list output
        id: ruff-lint
        run: uv tool run ruff check /home/runner/work/web/web/page/src --output-format=github
